### ISSUE TITLE
QTGMC Average Frames Error Fix

### ISSUE THREAD

**Issue by ReclusiveEagle** [HomeOfVapourSynthEvolution/havsfunc#43]
This line breaks QTGMC on the 2021 master havsfunc:
return clip.std.AverageFrames(weights=weights, scenechange=scenechange, planes=planes)

resulting in this error:

> if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00 File "C:/havsfunc.py", line 5321, in AverageFrames return clip.std.AverageFrames(weights=weights, scenechange=scenechange, planes=planes) File "src\cython\vapoursynth.pyx", line 1932, in vapoursynth.Plugin.__getattr__ AttributeError: There is no function named AverageFrames

The way to fix this is to return the string to its 2020 release line. It should be:

return clip.**misc**.AverageFrames(weights=weights, scenechange=scenechange, planes=planes)

**Comment by HolyWu** [comment]
It means your VapourSynth version is outdated.

**Comment by ReclusiveEagle** [comment]
> It means your VapourSynth version is outdated.

Updating to the latest everything and redownloading gives a new error:


2021-10-22 03:08:28.350
Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "script_42", line 18, in 
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 1179, in QTGMC
    if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5320, in AverageFrames
    clip = SCDetect(clip, threshold=scenechange)
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5635, in SCDetect
    sc = sc.misc.SCDetect(threshold=threshold)
  File "src\cython\vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc

Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "script_42", line 18, in 
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 1179, in QTGMC
    if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5320, in AverageFrames
    clip = SCDetect(clip, threshold=scenechange)
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5635, in SCDetect
    sc = sc.misc.SCDetect(threshold=threshold)
  File "src\cython\vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc

2021-10-22 03:08:37.923
Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "script_42", line 18, in 
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 1179, in QTGMC
    if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5320, in AverageFrames
    clip = SCDetect(clip, threshold=scenechange)
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5635, in SCDetect
    sc = sc.misc.SCDetect(threshold=threshold)
  File "src\cython\vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc

Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "script_42", line 18, in 
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 1179, in QTGMC
    if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5320, in AverageFrames
    clip = SCDetect(clip, threshold=scenechange)
  File "C:\Users\Reclusive Eagle\Downloads\New folder (6)\havsfunc.py", line 5635, in SCDetect
    sc = sc.misc.SCDetect(threshold=threshold)
  File "src\cython\vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc

Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "script_42", line 18, in 
  File "C:\folder\havsfunc.py", line 1179, in QTGMC
    if TR0 > 0: ts1 = AverageFrames(bobbed, weights=[1] * 3, scenechange=28 / 255, planes=CMplanes) # 0.00  0.33  0.33  0.33  0.00
  File "C:\folder\havsfunc.py", line 5320, in AverageFrames
    clip = SCDetect(clip, threshold=scenechange)
  File "C:\folder\havsfunc.py", line 5635, in SCDetect
    sc = sc.misc.SCDetect(threshold=threshold)
  File "src\cython\vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc

This is on Portable VS and embedded Python

**Comment by HolyWu** [comment]
[Some filters were moved to separate repositories.](https://github.com/orgs/vapoursynth/repositories)
