### ISSUE TITLE
Analyse: Function does not take argument(s) named _lambda, _global

### ISSUE THREAD

**Issue by TRPB** [HomeOfVapourSynthEvolution/havsfunc#44]
I'm trying to run the QTGMC function with the following script:

```
import vapoursynth as vs
import havsfunc as haf
import os


core = vs.core
clip = core.ffms2.Source(source=os.getenv('DEINTFILE'))
clip = haf.QTGMC(clip, Preset='Slow', TFF=True)
clip.set_output()
```

It gives me the following error:

```
Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
  File "src/cython/vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
  File "/home/tom/deint.vpy", line 8, in <module>
    clip = haf.QTGMC(clip, Preset='Slow', TFF=True)
  File "/usr/lib/python3.9/site-packages/havsfunc.py", line 1215, in QTGMC
    bVec1 = srchSuper.mv.Analyse(isb=True, delta=1, **analyse_args)
  File "src/cython/vapoursynth.pyx", line 2551, in vapoursynth.Function.__call__
vapoursynth.Error: Analyse: Function does not take argument(s) named _lambda, _global
```

It looks like an error in the code, unfortunately, I don't know enough about python or how it is supposed to work  to try to fix it.

**Comment by HolyWu** [comment]
Already fixed in https://github.com/HomeOfVapourSynthEvolution/havsfunc/commit/b36f5e76fc0958a862ef6946faf64232d03aba77 and https://github.com/HomeOfVapourSynthEvolution/havsfunc/commit/3b6a80ce502e6775c70df6bb2d19124de149073f.
