### ISSUE TITLE
ContraSharpening error

### ISSUE THREAD

**Issue by feniceyao** [HomeOfVapourSynthEvolution/havsfunc#45]
When using ContraSharpening, the error message says as the follows

Failed to evaluate the script:
Python exception: No attribute with the name rgvs exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "D:/Program Files/Video Process/VapourSynthEditor-r19-64bit/VideoExtract_SVP.vpy", line 17, in 
src = haf.ContraSharpening(srcd, srco, radius=2)
File "D:\Program Files\Python39\lib\site-packages\havsfunc.py", line 5688, in ContraSharpening
ssDD = core.rgvs.Repair(ssD, allD, mode=[rep if i in planes else 0 for i in range(denoised.format.num_planes)]) # limit the difference to the max of what the denoising removed locally
File "src\cython\vapoursynth.pyx", line 2385, in vapoursynth._CoreProxy.__getattr__
File "src\cython\vapoursynth.pyx", line 2228, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name rgvs exists. Did you mistype a plugin namespace?

**Comment by HolyWu** [comment]
https://github.com/vapoursynth/vs-removegrain
