### ISSUE TITLE
"Stab" doesn't work properly on some material

### ISSUE THREAD

**Issue by BlohoJo** [HomeOfVapourSynthEvolution/havsfunc#50]
I included an example... the clip jerks all over the place with the Stab filter enabled for no apparent reason. Increse the max x/y shift to 10 to see it better.

This doesn't happen with the AviSynth version of Stab.

I attached a clip that exhibits the issue (github doesn't let me attach, used zippyshare).

I also attached the script and plugins that I am using in AviSynth and Vapoursynth, just to rule out any version issues.

Clip -> https://www101.zippyshare.com/v/6IlzcOER/file.html
[avisynthPlugins.zip](https://github.com/HomeOfVapourSynthEvolution/havsfunc/files/7875678/avisynthPlugins.zip)
[vsfilters.zip](https://github.com/HomeOfVapourSynthEvolution/havsfunc/files/7875679/vsfilters.zip)

**Comment by HolyWu** [comment]
The Depan filter in MVTools plugin does not support `range` parameter. I guess it's affected by that. You can try https://github.com/theChaosCoder/lostfunc/blob/0a6816844b8f08ecac0e7a5bb32aacae2f4a3b93/lostfunc.py#L58 which supports `range` parameter, but I don't know where you can download the Depan plugin since the original repo has been lost in the limbo.

**Comment by BlohoJo** [comment]
Yeah, it looks like it's not going to work without DePanEstimate.dll. What I'm not understanding, is that isn't DePan.dll and DePanEstimate.dll [part of libmvtools.dll](https://forum.doom9.org/showthread.php?t=171207)?

**Comment by theChaosCoder** [comment]
I restored the Depan source code (hopefully it's the latest version) and the binary here: https://github.com/Vapoursynth-Plugins-Gitify/DePan
Will add it to vsrepo soon.

**Comment by Jieiku** [comment]
seems it don't load at all anymore?

```
import vapoursynth as vs
import havsfunc as haf
core = vs.core
src = core.ffms2.Source(source='/media/storage/video.mkv')
src = haf.Stab(src,8,8,15)
src.set_output()
```
error log:
```
Failed to evaluate the script:
Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "/home/jieiku/scripts/vpy/enc-mkv.vpy", line 6, in 
src = haf.Stab(src,8,8,15)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 3461, in Stab
temp = AverageFrames(clp, weights=[1] * 15, scenechange=25 / 255)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 5800, in AverageFrames
clip = SCDetect(clip, threshold=scenechange)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 6122, in SCDetect
sc = sc.misc.SCDetect(threshold=threshold)
File "src/cython/vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc
```
