### ISSUE TITLE
QTGMC: There is no function named Bob

### ISSUE THREAD

**Issue by iamtherobin** [HomeOfVapourSynthEvolution/havsfunc#66]
Windows 7, Python 3.8.12, Vapoursynth R58, havsfunc git 1376c9e

Any attempt to use InputType=0 with QTGMC throws the following:

```
Failed to evaluate the script:
Python exception: There is no function named Bob

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "D:\Cream Lemon\VPY Scripts\Amis Journey Complete (new) (no denoise).vpy", line 13, in 
File "C:\Users\ROBN\AppData\Roaming\Python\Python38\site-packages\havsfunc.py", line 1678, in QTGMC
bobbed = clip.resize.Bob(tff=TFF, filter_param_a=0, filter_param_b=0.5)
File "src\cython\vapoursynth.pyx", line 2413, in vapoursynth.Plugin.__getattr__
AttributeError: There is no function named BobFailed to evaluate the script:
Python exception: There is no function named Bob

```

I do not have a Bob function for resize and Vapoursynth doc's do not list a Bob for resize. Where is this function coming from?

**Comment by shssoichiro** [comment]
This error was fixed for me after I upgraded Vapoursynth from R57 to R58. Can you verify your system is using your R58 installation with `vspipe --version`?

Vapoursynth's docs on their website have, for whatever reason, not been updated for R58.

**Comment by iamtherobin** [comment]
You're right. I downgraded to R57 when troubleshooting the previous tickets I submitted and looks like I forgot to upgrade back to R58.
