### ISSUE TITLE
stab() no longer loads/works

### ISSUE THREAD

**Issue by Jieiku** [HomeOfVapourSynthEvolution/havsfunc#68]
seems it don't load at all anymore?

```
import vapoursynth as vs
import havsfunc as haf
core = vs.core
src = core.ffms2.Source(source='/media/storage/video.mkv')
src = haf.Stab(src,8,8,15)
src.set_output()
```
error log:
```
Failed to evaluate the script:
Python exception: There is no attribute or namespace named misc

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "/home/jieiku/scripts/vpy/enc-mkv.vpy", line 6, in 
src = haf.Stab(src,8,8,15)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 3461, in Stab
temp = AverageFrames(clp, weights=[1] * 15, scenechange=25 / 255)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 5800, in AverageFrames
clip = SCDetect(clip, threshold=scenechange)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 6122, in SCDetect
sc = sc.misc.SCDetect(threshold=threshold)
File "src/cython/vapoursynth.pyx", line 1774, in vapoursynth.VideoNode.__getattr__
AttributeError: There is no attribute or namespace named misc
```

**Comment by dnjulek** [comment]
Install misc
https://github.com/vapoursynth/vs-miscfilters-obsolete/releases

**Comment by Jieiku** [comment]
THANK YOU! I really appreciate the help. I got that installed and now its a different error:
```
Failed to evaluate the script:
Python exception: No attribute with the name rgvs exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "/home/jieiku/scripts/vpy/enc-mkv.vpy", line 10, in 
video = haf.Stab(video,8,8,15)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 3462, in Stab
inter = core.std.Interleave([core.rgvs.Repair(temp, AverageFrames(clp, weights=[1] * 3, scenechange=25 / 255), mode=[1]), clp])
File "src/cython/vapoursynth.pyx", line 2385, in vapoursynth._CoreProxy.__getattr__
File "src/cython/vapoursynth.pyx", line 2228, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name rgvs exists. Did you mistype a plugin namespace?
```
