### ISSUE TITLE
EdgeCleaner: "No attribute with the name rgvs exists. Did you mistype a plugin namespace?"

### ISSUE THREAD

**Issue by EvgenyKV** [HomeOfVapourSynthEvolution/havsfunc#77]
```
Failed to evaluate the script:
Python exception: No attribute with the name rgvs exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src/cython/vapoursynth.pyx", line 2890, in vapoursynth._vpy_evaluate
File "src/cython/vapoursynth.pyx", line 2891, in vapoursynth._vpy_evaluate
File "/disk/script.vpy", line 36, in 
#v = haf.EdgeCleaner(v)
File "/usr/lib/python3.10/site-packages/havsfunc.py", line 551, in EdgeCleaner
main = core.rgvs.Repair(main, c, mode=rmode)
File "src/cython/vapoursynth.pyx", line 2438, in vapoursynth._CoreProxy.__getattr__
File "src/cython/vapoursynth.pyx", line 2280, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name rgvs exists. Did you mistype a plugin namespace?
```
havsfunc from https://aur.archlinux.org/packages/vapoursynth-plugin-havsfunc-git

**Comment by shssoichiro** [comment]
You need to also install https://aur.archlinux.org/packages/vapoursynth-plugin-removegrain-git, this should be added as a dependency to the havsfunc-git package as well
